name: Deploy Multidocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: actions/checkout@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t essentylz/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true essentylz/react-test npm test

      - run: docker build -t essentylz/multi-client ./client
      - run: docker build -t essentylz/multi-nginx ./nginx
      - run: docker build -t essentylz/multi-server ./server
      - run: docker build -t essentylz/multi-worker ./worker

      - run: docker push essentylz/multi-client
      - run: docker push essentylz/multi-nginx
      - run: docker push essentylz/multi-server
      - run: docker push essentylz/multi-worker
