name: Deploy Multidocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: actions/checkout@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t raghavendra31789/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true raghavendra31789/react-test npm test

      - run: docker build -t raghavendra31789/multi-client ./client
      - run: docker build -t raghavendra31789/multi-nginx ./nginx
      - run: docker build -t raghavendra31789/multi-server ./server
      - run: docker build -t raghavendra31789/multi-worker ./worker

    - name:
      uses: actions/checkout@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push raghavendra31789/multi-client
      - run: docker push raghavendra31789/multi-nginx
      - run: docker push raghavendra31789/multi-server
      - run: docker push raghavendra31789/multi-worker
